import type { Service } from '@/types'

export const services: Service[] = [
  // INTRADAY ALPHA
  {
    id: 'intraday-alpha-1m',
    title: 'Intraday Alpha — 1 Month',
    category: 'Equity Cash',
    duration: '1 Month',
    price: '₹5,000',
    tag: 'Most Popular',
    description: 'Intraday Alpha is a cash-market intraday trading research service designed for traders looking to capture short-term opportunities within the same trading day. Our research professionals analyze market movements using structured technical methods to identify high-potential trading setups.',
    features: [
      '1–2 intraday trades per day',
      'Same day exit — no overnight risk',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Real-time trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'intraday-alpha-3m',
    title: 'Intraday Alpha — 3 Months',
    category: 'Equity Cash',
    duration: '3 Months',
    price: '₹12,000',
    tag: 'Best Value',
    description: 'Intraday Alpha is a cash-market intraday trading research service designed for traders looking to capture short-term opportunities within the same trading day. Our research professionals analyze market movements using structured technical methods to identify high-potential trading setups.',
    features: [
      '1–2 intraday trades per day',
      'Same day exit — no overnight risk',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Real-time trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'intraday-alpha-1y',
    title: 'Intraday Alpha — Annual',
    category: 'Equity Cash',
    duration: '12 Months',
    price: '₹36,000',
    tag: null,
    description: 'Intraday Alpha is a cash-market intraday trading research service designed for traders looking to capture short-term opportunities within the same trading day. Our research professionals analyze market movements using structured technical methods to identify high-potential trading setups.',
    features: [
      '1–2 intraday trades per day',
      'Same day exit — no overnight risk',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Real-time trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },

  // BTST ALPHA
  {
    id: 'btst-alpha-1m',
    title: 'BTST Alpha — 1 Month',
    category: 'Equity Premium',
    duration: '1 Month',
    price: '₹5,000',
    tag: 'Most Popular',
    description: 'BTST Alpha (Buy Today, Sell Tomorrow) is designed for traders who want to benefit from potential overnight price momentum in carefully selected stocks. Take a position near the end of the trading session and exit the next day to capture favourable price movements.',
    features: [
      '1 high-conviction BTST trade per day',
      'Exit next morning',
      'Alerts issued 2:45 PM – 3:15 PM',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'btst-alpha-3m',
    title: 'BTST Alpha — 3 Months',
    category: 'Equity Premium',
    duration: '3 Months',
    price: '₹12,000',
    tag: 'Best Value',
    description: 'BTST Alpha (Buy Today, Sell Tomorrow) is designed for traders who want to benefit from potential overnight price momentum in carefully selected stocks. Take a position near the end of the trading session and exit the next day to capture favourable price movements.',
    features: [
      '1 high-conviction BTST trade per day',
      'Exit next morning',
      'Alerts issued 2:45 PM – 3:15 PM',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'btst-alpha-1y',
    title: 'BTST Alpha — Annual',
    category: 'Equity Premium',
    duration: '12 Months',
    price: '₹36,000',
    tag: null,
    description: 'BTST Alpha (Buy Today, Sell Tomorrow) is designed for traders who want to benefit from potential overnight price momentum in carefully selected stocks. Take a position near the end of the trading session and exit the next day to capture favourable price movements.',
    features: [
      '1 high-conviction BTST trade per day',
      'Exit next morning',
      'Alerts issued 2:45 PM – 3:15 PM',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Research report included',
      'Dedicated support',
    ],
  },

  // POSITIONAL ALPHA
  {
    id: 'positional-alpha-1m',
    title: 'Positional Alpha — 1 Month',
    category: 'F&O',
    duration: '1 Month',
    price: '₹6,000',
    tag: null,
    description: 'Positional Alpha is a positional trading research service designed for traders who want to benefit from short-term market trends without the pressure of daily trading. Hold stocks for several days to a few weeks to capture meaningful price movements.',
    features: [
      '3–4 trades per month',
      'Holding period approx. 2 weeks',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Ongoing trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'positional-alpha-3m',
    title: 'Positional Alpha — 3 Months',
    category: 'F&O',
    duration: '3 Months',
    price: '₹15,000',
    tag: 'Best Value',
    description: 'Positional Alpha is a positional trading research service designed for traders who want to benefit from short-term market trends without the pressure of daily trading. Hold stocks for several days to a few weeks to capture meaningful price movements.',
    features: [
      '3–4 trades per month',
      'Holding period approx. 2 weeks',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Ongoing trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
  {
    id: 'positional-alpha-1y',
    title: 'Positional Alpha — Annual',
    category: 'F&O',
    duration: '12 Months',
    price: '₹48,000',
    tag: null,
    description: 'Positional Alpha is a positional trading research service designed for traders who want to benefit from short-term market trends without the pressure of daily trading. Hold stocks for several days to a few weeks to capture meaningful price movements.',
    features: [
      '3–4 trades per month',
      'Holding period approx. 2 weeks',
      'WhatsApp & Telegram alerts',
      'Entry, target & stop-loss defined',
      'Ongoing trade updates',
      'Research report included',
      'Dedicated support',
    ],
  },
]
