import type { Service } from '@/types'

export const services: Service[] = [
  {
    id: 'eq-cash-1m',
    title: 'Equity Research — 1 Month',
    category: 'Equity Research',
    duration: '30 Days',
    price: '₹4,999',
    tag: 'Most Popular',
    description: 'Our flagship monthly equity cash plan with 2–3 high-conviction calls per day, full research backing, and dedicated support.',
    features: ['2–3 calls per day', 'WhatsApp alerts', 'Entry, target & stop-loss', 'Research report included', 'Dedicated support'],
  },
  {
    id: 'eq-cash-10d',
    title: 'Equity Research — 10 Days',
    category: 'Equity Research',
    duration: '10 Days',
    price: '₹1,999',
    tag: 'Best Value',
    description: 'Perfect for short-term traders who want to experience our equity cash service over 10 active trading days.',
    features: ['2–3 calls per day', 'WhatsApp alerts', 'Entry, target & stop-loss', 'Priority support'],
  },
  {
    id: 'eq-cash-1w',
    title: 'Equity Research — 1 Week',
    category: 'Equity Research',
    duration: '7 Days',
    price: '₹999',
    tag: null,
    description: 'Try our equity cash service for a full trading week with live calls and real-time alerts.',
    features: ['2–3 calls per day', 'WhatsApp alerts', 'Entry, target & stop-loss'],
  },
  {
    id: 'eq-premium-1m',
    title: 'Market insights — 1 Month',
    category: 'Market insights',
    duration: '30 Days',
    price: '₹8,999',
    tag: 'Most Popular',
    description: 'Our elite premium plan with higher-conviction calls, portfolio review, and one-on-one consultation included.',
    features: ['4–5 calls per day', 'Priority WhatsApp', 'Entry, target & stop-loss', 'Weekly research report', 'One-on-one consultation', 'Portfolio review'],
  },
  {
    id: 'eq-premium-10d',
    title: 'Market insights — 10 Days',
    category: 'Market insights',
    duration: '10 Days',
    price: '₹3,499',
    tag: null,
    description: 'Premium calls for 10 high-conviction trading days with full research reports and priority alerts.',
    features: ['4–5 calls per day', 'Priority alerts', 'Entry, target & stop-loss', 'Research reports'],
  },
  {
    id: 'fo-1m',
    title: 'Investment recommendations — 1 Month',
    category: 'Investment recommendations',
    duration: '30 Days',
    price: '₹11,999',
    tag: null,
    description: 'Comprehensive Futures and Options advisory with clearly defined strategies for both index and stock options.',
    features: ['2–3 F&O calls per day', 'Index & stock options', 'Hedging strategies', 'Risk management', 'Research reports', 'Dedicated RM'],
  },
  {
    id: 'fo-1w',
    title: 'Investment recommendations — 1 Week',
    category: 'Investment recommendations',
    duration: '7 Days',
    price: '₹3,999',
    tag: 'Best Value',
    description: 'Experience our F&O advisory service for one full trading week with live strategy calls.',
    features: ['2–3 F&O calls per day', 'Index & stock options', 'Stop-loss defined'],
  },
  {
    id: 'demo',
    title: 'Free Demo Service',
    category: 'Demo',
    duration: '2 Days',
    price: 'FREE',
    tag: 'Free Trial',
    description: 'Experience Fortune Kraft before you invest. Get 2 days of live equity calls with no payment required.',
    features: ['1–2 live calls', 'WhatsApp alerts', 'Entry, target & stop-loss', 'No payment required'],
  },
]
